name: Deployment

on: push

jobs:
  dev:
    name: Dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
  staging:
    name: Staging
    runs-on: ubuntu-latest
    needs:
      - dev
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  prod:
    name: Prod
    runs-on: ubuntu-latest
    needs:
      - staging
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2